### ISSUE TITLE
[BUG] Exception caused NeuralNetFastAI_BAG_L1 to fail during training?

### ISSUE THREAD

**Issue by lovechang1986** [awslabs/autogluon#2057] opened 2022-08-20 07:45 UTC
**Describe the bug**
I'm try to training the best_quaility model, but NeuralNetFastAI_BAG_L1 model skipped and raise error infomation, Anyone know some error occured?

I installed the pytorch based on CPU, but I don't know why the version seems like GPU version?
The version infomation:
```
INSTALLED VERSIONS
------------------
date                   : 2022-08-20
time                   : 15:33:04.050760
python                 : 3.9.7.final.0
OS                     : Linux
OS-release             : 3.10.0-957.el7.x86_64
Version                : #1 SMP Thu Oct 4 20:48:51 UTC 2018
machine                : x86_64
processor              : x86_64
num_cores              : 32
cpu_ram_mb             : 386415
cuda version           : None
num_gpus               : 0
gpu_ram_mb             : []
avail_disk_size_mb     : 870718

autogluon.common       : 0.5.0
autogluon.core         : 0.5.0
autogluon.features     : 0.5.0
autogluon.multimodal   : 0.5.0
autogluon.tabular      : 0.5.0
autogluon.text         : 0.5.0
autogluon.timeseries   : None
autogluon.vision       : 0.5.0
autogluon_contrib_nlp  : None
boto3                  : 1.24.23
catboost               : 1.0.6
dask                   : 2021.11.2
distributed            : 2021.11.2
fairscale              : 0.4.6
fastai                 : 2.5.6
gluoncv                : 0.11.0
hyperopt               : 0.2.7
lightgbm               : 3.3.2
matplotlib             : 3.5.2
networkx               : 2.8.4
nlpaug                 : 1.1.10
nltk                   : 3.7
nptyping               : 1.4.4
numpy                  : 1.21.6
omegaconf              : 2.1.2
pandas                 : 1.4.3
PIL                    : 9.0.1
protobuf               : None
psutil                 : 5.8.0
pytorch-metric-learning: None
pytorch_lightning      : 1.6.4
ray                    : 1.13.0
requests               : 2.28.1
scipy                  : 1.7.3
sentencepiece          : None
skimage                : 0.19.3
sklearn                : 1.0.2
smart_open             : 5.2.1
timm                   : 0.5.4
torch                  : 1.11.0+cu102
torchmetrics           : 0.7.3
tqdm                   : 4.64.0
transformers           : 4.20.1
xgboost                : 1.4.2

```
The error infomation:
```
Fitting model: NeuralNetFastAI_BAG_L1 ...
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy
	Warning: Exception caused NeuralNetFastAI_BAG_L1 to fail during training... Skipping this model.
		[36mray::_ray_fit()[39m (pid=42591, ip=192.168.2.84)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 289, in _ray_fit
    fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold,
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 579, in fit
    out = self._fit(**kwargs)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/fastainn/tabular_nn_fastai.py", line 284, in _fit
    self.model.fit_one_cycle(epochs, params['lr'], cbs=callbacks)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/fastai/callback/schedule.py", line 116, in fit_one_cycle
    self.fit(n_epoch, cbs=ParamScheduler(scheds)+L(cbs), reset_opt=reset_opt, wd=wd)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/fastai/learner.py", line 221, in fit
    self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/fastai/learner.py", line 165, in _with_events
    self(f'after_{event_type}');  final()
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/fastai/learner.py", line 141, in __call__
    def __call__(self, event_name): L(event_name).map(self._call_one)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/fastcore/foundation.py", line 155, in map
    def map(self, f, *args, gen=False, **kwargs): return self._new(map_ex(self, f, *args, gen=gen, **kwargs))
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/fastcore/basics.py", line 790, in map_ex
    return list(res)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/fastcore/basics.py", line 775, in __call__
    return self.func(*fargs, **kwargs)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/fastai/learner.py", line 145, in _call_one
    for cb in self.cbs.sorted('order'): cb(event_name)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/fastai/callback/core.py", line 57, in __call__
    try: res = getattr(self, event_name, noop)()
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/fastainn/callbacks.py", line 107, in after_fit
    self.learn.load(f'{self.fname}', with_opt=self.with_opt)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/fastai/learner.py", line 361, in load
    load_model(file, self.model, self.opt, device=device, **kwargs)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/fastai/learner.py", line 48, in load_model
    state = torch.load(file, map_location=device)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp0_e7r9lx/models/model.pth'
Detailed Traceback:
Traceback (most recent call last):
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1086, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1044, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 579, in fit
    out = self._fit(**kwargs)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py", line 153, in _fit
    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 232, in _fit
    self._fit_folds(X=X, y=y, model_base=model_base, X_pseudo=X_pseudo, y_pseudo=y_pseudo,
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 503, in _fit_folds
    fold_fitting_strategy.after_all_folds_scheduled()
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 468, in after_all_folds_scheduled
    raise processed_exception
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 436, in after_all_folds_scheduled
    time_end_fit, predict_time, predict_1_time = self.ray.get(finished)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/ray/worker.py", line 1831, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(FileNotFoundError): [36mray::_ray_fit()[39m (pid=42591, ip=192.168.2.84)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 289, in _ray_fit
    fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold,
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 579, in fit
    out = self._fit(**kwargs)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/fastainn/tabular_nn_fastai.py", line 284, in _fit
    self.model.fit_one_cycle(epochs, params['lr'], cbs=callbacks)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/fastai/callback/schedule.py", line 116, in fit_one_cycle
    self.fit(n_epoch, cbs=ParamScheduler(scheds)+L(cbs), reset_opt=reset_opt, wd=wd)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/fastai/learner.py", line 221, in fit
    self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/fastai/learner.py", line 165, in _with_events
    self(f'after_{event_type}');  final()
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/fastai/learner.py", line 141, in __call__
    def __call__(self, event_name): L(event_name).map(self._call_one)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/fastcore/foundation.py", line 155, in map
    def map(self, f, *args, gen=False, **kwargs): return self._new(map_ex(self, f, *args, gen=gen, **kwargs))
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/fastcore/basics.py", line 790, in map_ex
    return list(res)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/fastcore/basics.py", line 775, in __call__
    return self.func(*fargs, **kwargs)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/fastai/learner.py", line 145, in _call_one
    for cb in self.cbs.sorted('order'): cb(event_name)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/fastai/callback/core.py", line 57, in __call__
    try: res = getattr(self, event_name, noop)()
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/tabular/models/fastainn/callbacks.py", line 107, in after_fit
    self.learn.load(f'{self.fname}', with_opt=self.with_opt)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/fastai/learner.py", line 361, in load
    load_model(file, self.model, self.opt, device=device, **kwargs)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/fastai/learner.py", line 48, in load_model
    state = torch.load(file, map_location=device)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/anaconda3/envs/autogluon/lib/python3.9/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp0_e7r9lx/models/model.pth'
```

**Comment by Innixma** [comment] 2022-08-25 00:22
Can you please provide the full code + logs you used to produce this error? This will help to identify the problem.

If possible, try to reproduce on a publicly available dataset, and consider seeing if the issue occurs in a colab notebook.

**Comment by aalokpatwa** [comment] 2022-08-25 01:40
Having the same issue -- crashes my Jupyter notebook kernel too

**Comment by lovechang1986** [comment] 2022-08-29 04:06
Why I install the pytorch follow official docs. it can't match the pytorch 1.2.0?
I installed the version manually and then prompted me for a FASTAI conflict:sob:

**Comment by Innixma** [comment] 2022-11-08 19:53
This may have been fixed in mainline branch with the upgrade to Ray 2.0, but it is hard to tell as I could never reproduce this issue on my end. I am resolving this issue for now. If the issue persists in mainline source build, please re-open and provide a reproducible example.

**Closed by Innixma** 2022-11-08 19:53 UTC
Labels: bug, module: tabular, Needs Triage

**Comment by liubola** [comment] 2023-03-07 23:12
If the loss is na at epoch 0, you will encounter this problem, indicating that it is a data issue rather than a bug.

**Comment by TreeOfLearning** [comment] 2024-07-25 13:13
I am experiencing this issue too. It must be a data issue somehow because I can't reproduce it with a public dataset, but I'm not sure what the issue is - my data is not sparse, and is cleaned of nans and constrained to float32 range. All other model types are working just fine! I'd love some input on how to debug this.
