### ISSUE TITLE
[BUG] Segmentation fault while importing TextPredictor

### ISSUE THREAD

**Issue by cjj490168650** [awslabs/autogluon#1762] opened 2022-05-28 12:06 UTC
- [X] I have checked that this bug exists on the latest stable version of AutoGluon
- [ ] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**

```
>>> from autogluon.text import TextPredictor
/home/cjj/anaconda3/envs/pytorch/lib/python3.9/site-packages/torchvision/io/image.py:11: UserWarning: Failed to load image Python extension: libc10_cuda.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Segmentation fault (core dumped)
```

**Expected behavior**

import TextPredictor

**To Reproduce**

```python
from autogluon.text import TextPredictor
```

**Screenshots**

![QQ图片20220528200354](https://user-images.githubusercontent.com/45029740/170824684-b4396233-6298-4e57-954d-137802573218.png)

**Installed Versions**

<details>

```
/home/cjj/anaconda3/envs/pytorch/lib/python3.9/site-packages/torchvision/io/image.py:11: UserWarning: Failed to load image Python extension: libc10_cuda.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
/home/cjj/anaconda3/envs/pytorch/lib/python3.9/site-packages/gluoncv/__init__.py:40: UserWarning: Both `mxnet==1.9.1` and `torch==1.10.2+cpu` are installed. You might encounter increased GPU memory footprint if both framework are used at the same time.
  warnings.warn(f'Both `mxnet=={mx.__version__}` and `torch=={torch.__version__}` are installed. '

INSTALLED VERSIONS
------------------
date                 : 2022-05-28
time                 : 08:05:29.672541
python               : 3.9.12.final.0
OS                   : Linux
OS-release           : 4.15.0-76-generic
Version              : #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020
machine              : x86_64
processor            : x86_64
num_cores            : 40
cpu_ram_mb           : 257841
cuda version         : 11.515.43.04
num_gpus             : 10
gpu_ram_mb           : [2886, 12195, 12195, 6636, 3766, 3766, 3766, 1598, 6930, 4332]
avail_disk_size_mb   : 1487138

autogluon.common     : 0.4.2b20220528
autogluon.core       : 0.4.2b20220528
autogluon.features   : 0.4.2b20220528
autogluon.tabular    : 0.4.1
autogluon.text       : 0.4.2b20220528
autogluon.vision     : 0.4.1
autogluon_contrib_nlp: 0.0.1
boto3                : 1.23.8
catboost             : 1.0.6
dask                 : 2021.11.2
distributed          : 2021.11.2
fairscale            : 0.4.6
fastai               : 2.5.6
gluoncv              : 0.11.0
lightgbm             : 3.3.2
matplotlib           : 3.5.2
networkx             : 2.8.2
nptyping             : 1.4.4
numpy                : 1.22.4
omegaconf            : 2.1.2
pandas               : 1.3.5
PIL                  : 9.0.1
psutil               : 5.8.0
pytorch_lightning    : 1.6.3
ray                  : 1.10.0
requests             : 2.27.1
scipy                : 1.7.3
sentencepiece        : None
setuptools           : 59.5.0
skimage              : 0.19.2
sklearn              : 1.0.2
smart_open           : 5.2.1
timm                 : 0.5.4
torch                : 1.10.2+cpu
torchmetrics         : 0.7.3
tqdm                 : 4.64.0
transformers         : 4.16.2
xgboost              : 1.4.2
```

</details>

**Comment by sxjscience** [comment] 2022-06-03 17:50
Just for sanity check. Are you able to import pytorch?

```python
import torch
a = torch.ones(10, 5)
print(a)
```

**Comment by damirpolat** [comment] 2022-06-03 20:38
I have a similar issue. I get the following error when running `from autogluon.text import TextPredictor`:

```
/local/home/user/.venv/autogluon/lib64/python3.7/site-packages/torchvision/io/image.py:11: UserWarning: Failed to load image Python extension: libc10_cuda.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
zsh: segmentation fault  python
```

My `pip freeze` output:
```
absl-py==1.0.0
aiohttp==3.8.1
aiosignal==1.2.0
antlr4-python3-runtime==4.8
async-timeout==4.0.2
asynctest==0.13.0
attrs==21.4.0
autocfg==0.0.8
autogluon==0.4.2
autogluon-contrib-nlp==0.0.1b20220208
autogluon.common==0.4.2
autogluon.core==0.4.2
autogluon.features==0.4.2
autogluon.tabular==0.4.2
autogluon.text==0.4.2
autogluon.vision==0.4.2
blis==0.7.7
boto3==1.23.9
botocore==1.26.10
cachetools==5.1.0
catalogue==1.0.0
catboost==1.0.6
certifi==2022.5.18.1
charset-normalizer==2.0.12
click==8.1.3
cloudpickle==2.1.0
colorama==0.4.4
contextvars==2.4
cycler==0.11.0
cymem==2.0.6
dask==2021.11.2
Deprecated==1.2.13
distributed==2021.11.2
et-xmlfile==1.1.0
fairscale==0.4.6
fastai==2.5.6
fastcore==1.4.3
fastdownload==0.0.6
fastprogress==1.0.2
filelock==3.7.0
flake8==4.0.1
fonttools==4.33.3
frozenlist==1.3.0
fsspec==2022.5.0
gluoncv==0.10.5.post0
google-auth==2.6.6
google-auth-oauthlib==0.4.6
graphviz==0.20
grpcio==1.46.3
HeapDict==1.0.1
huggingface-hub==0.7.0
idna==3.3
imageio==2.19.2
immutables==0.18
importlib-metadata==4.2.0
importlib-resources==5.7.1
Jinja2==3.1.2
jmespath==1.0.0
joblib==1.1.0
jsonschema==4.5.1
kiwisolver==1.4.2
lightgbm==3.3.2
locket==1.0.0
Markdown==3.3.4
MarkupSafe==2.1.1
matplotlib==3.5.2
mccabe==0.6.1
msgpack==1.0.4rc1
multidict==6.0.2
murmurhash==1.0.7
networkx==2.6.3
nptyping==1.4.4
numpy==1.21.6
oauthlib==3.2.0
omegaconf==2.1.2
opencv-python==4.5.5.64
openpyxl==3.0.10
packaging==21.3
pandas==1.3.5
partd==1.2.0
Pillow==9.0.1
plac==1.1.3
plotly==5.8.0
portalocker==2.4.0
preshed==3.0.6
protobuf==3.20.1
psutil==5.8.0
pyarrow==8.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.8.0
pyDeprecate==0.3.2
pyflakes==2.4.0
pyparsing==3.0.9
pyrsistent==0.18.1
python-dateutil==2.8.2
pytorch-lightning==1.6.3
pytz==2022.1
PyWavelets==1.3.0
PyYAML==6.0
ray==1.10.0
redis==4.3.1
regex==2022.4.24
requests==2.27.1
requests-oauthlib==1.3.1
rsa==4.8
s3transfer==0.5.2
sacrebleu==2.1.0
sacremoses==0.0.53
scikit-image==0.19.2
scikit-learn==1.0.2
scipy==1.7.3
sentencepiece==0.1.95
six==1.16.0
smart-open==5.2.1
sortedcontainers==2.4.0
spacy==2.3.7
srsly==1.0.5
tabulate==0.8.9
tblib==1.7.0
tenacity==8.0.1
tensorboard==2.9.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
thinc==7.4.5
threadpoolctl==3.1.0
tifffile==2021.11.2
timm==0.5.4
tokenizers==0.12.1
toolz==0.11.2
torch==1.10.2+cpu
torchaudio==0.10.2+cpu
torchmetrics==0.7.3
torchvision==0.11.3
tornado==6.1
tqdm==4.64.0
transformers==4.16.2
typing_extensions==4.2.0
typish==1.9.3
urllib3==1.26.9
wasabi==0.9.1
Werkzeug==2.1.2
wrapt==1.14.1
xgboost==1.4.2
yacs==0.1.8
yarl==1.7.2
zict==2.2.0
zipp==3.8.0
```

**Comment by sxjscience** [comment] 2022-06-03 20:39
@damirpolat @cjj490168650 Would you try the following version combination?

```bash
pip install autogluon==0.4.1 protobuf==3.18.1
```

**Comment by damirpolat** [comment] 2022-06-03 20:39
> Just for sanity check. Are you able to import pytorch?
> 
> ```python
> import torch
> a = torch.ones(10, 5)
> print(a)
> ```

It runs fine for me:

```
>>> import torch
>>> a = torch.ones(10, 5)
>>> print(a)
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
```

**Comment by damirpolat** [comment] 2022-06-03 20:50
> @damirpolat @cjj490168650 Would you try the following version combination?
> 
> ```shell
> pip install autogluon==0.4.1 protobuf==3.18.1
> ```

It works now! However I still get the warning:

```
>>> from autogluon.text import TextPredictor
/local/home/user/.venv/autogluon/lib64/python3.7/site-packages/torchvision/io/image.py:11: UserWarning: Failed to load image Python extension: libc10_cuda.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
```

But works fine otherwise.


Thank you!

**Comment by Innixma** [comment] 2022-06-03 20:57
@damirpolat Great! Can you also try (on separate lines):

```
pip install autogluon==0.4.2
pip install protobuf==3.18.1
```

I believe this should also work, but want to confirm.

**Comment by damirpolat** [comment] 2022-06-03 20:57
`pip freeze` of the working version:

```
absl-py==1.0.0
aiohttp==3.8.1
aiosignal==1.2.0
antlr4-python3-runtime==4.8
async-timeout==4.0.2
asynctest==0.13.0
attrs==21.4.0
autocfg==0.0.8
autogluon==0.4.1
autogluon-contrib-nlp==0.0.1b20220208
autogluon.common==0.4.1
autogluon.core==0.4.1
autogluon.features==0.4.1
autogluon.tabular==0.4.1
autogluon.text==0.4.1
autogluon.vision==0.4.1
blis==0.7.7
boto3==1.23.9
botocore==1.26.10
cachetools==5.1.0
catalogue==1.0.0
catboost==1.0.6
certifi==2022.5.18.1
charset-normalizer==2.0.12
click==8.1.3
cloudpickle==2.1.0
colorama==0.4.4
contextvars==2.4
cycler==0.11.0
cymem==2.0.6
dask==2021.11.2
Deprecated==1.2.13
distributed==2021.11.2
et-xmlfile==1.1.0
fairscale==0.4.6
fastai==2.5.6
fastcore==1.4.3
fastdownload==0.0.6
fastprogress==1.0.2
filelock==3.7.0
flake8==4.0.1
fonttools==4.33.3
frozenlist==1.3.0
fsspec==2022.5.0
gluoncv==0.10.5.post0
google-auth==2.6.6
google-auth-oauthlib==0.4.6
graphviz==0.20
grpcio==1.46.3
HeapDict==1.0.1
huggingface-hub==0.7.0
idna==3.3
imageio==2.19.2
immutables==0.18
importlib-metadata==4.2.0
importlib-resources==5.7.1
Jinja2==3.1.2
jmespath==1.0.0
joblib==1.1.0
jsonschema==4.5.1
kiwisolver==1.4.2
lightgbm==3.3.2
locket==1.0.0
Markdown==3.3.4
MarkupSafe==2.1.1
matplotlib==3.5.2
mccabe==0.6.1
msgpack==1.0.4rc1
multidict==6.0.2
murmurhash==1.0.7
networkx==2.6.3
nptyping==1.4.4
numpy==1.21.6
oauthlib==3.2.0
omegaconf==2.1.2
opencv-python==4.5.5.64
openpyxl==3.0.10
packaging==21.3
pandas==1.3.5
partd==1.2.0
Pillow==9.0.1
plac==1.1.3
plotly==5.8.0
portalocker==2.4.0
preshed==3.0.6
protobuf==3.18.1
psutil==5.8.0
pyarrow==8.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.8.0
pyDeprecate==0.3.2
pyflakes==2.4.0
pyparsing==3.0.9
pyrsistent==0.18.1
python-dateutil==2.8.2
pytorch-lightning==1.6.3
pytz==2022.1
PyWavelets==1.3.0
PyYAML==6.0
ray==1.10.0
redis==4.3.1
regex==2022.4.24
requests==2.27.1
requests-oauthlib==1.3.1
rsa==4.8
s3transfer==0.5.2
sacrebleu==2.1.0
sacremoses==0.0.53
scikit-image==0.19.2
scikit-learn==1.0.2
scipy==1.7.3
sentencepiece==0.1.95
six==1.16.0
smart-open==5.2.1
sortedcontainers==2.4.0
spacy==2.3.7
srsly==1.0.5
tabulate==0.8.9
tblib==1.7.0
tenacity==8.0.1
tensorboard==2.9.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
thinc==7.4.5
threadpoolctl==3.1.0
tifffile==2021.11.2
timm==0.5.4
tokenizers==0.12.1
toolz==0.11.2
torch==1.10.2+cpu
torchaudio==0.10.2+cpu
torchmetrics==0.7.3
torchvision==0.11.3
tornado==6.1
tqdm==4.64.0
transformers==4.16.2
typing_extensions==4.2.0
typish==1.9.3
urllib3==1.26.9
wasabi==0.9.1
Werkzeug==2.1.2
wrapt==1.14.1
xgboost==1.4.2
yacs==0.1.8
yarl==1.7.2
zict==2.2.0
zipp==3.8.0

```

**Comment by damirpolat** [comment] 2022-06-03 21:08
> @damirpolat Great! Can you also try (on separate lines):
> 
> ```
> pip install autogluon==0.4.2
> pip install protobuf==3.18.1
> ```
> 
> I believe this should also work, but want to confirm.

It gave me this error when installing protobuf:
```
Collecting protobuf==3.18.1
  Using cached protobuf-3.18.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.1
    Uninstalling protobuf-3.20.1:
      Successfully uninstalled protobuf-3.20.1
ERROR: pip’s dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
autogluon-core 0.4.2 requires protobuf<3.21,>=3.20, but you have protobuf 3.18.1 which is incompatible.
Successfully installed protobuf-3.18.1
```

But worked otherwise!

**Comment by sxjscience** [comment] 2022-06-03 21:59
Actually, I'm unable to reproduce the error in my EC2 instance.

**Comment by cjj490168650** [comment] 2022-06-04 02:12
> @damirpolat Great! Can you also try (on separate lines):
> 
> ```
> pip install autogluon==0.4.2
> pip install protobuf==3.18.1
> ```
> 
> I believe this should also work, but want to confirm.

it works

**Comment by yinweisu** [comment] 2022-06-06 23:52
Instead of downgrading `protobuf`. Make sure to update the python toolchains:
```python
pip3 install -U pip
pip3 install -U setuptools wheel
```
then install autogluon.

Tested on both a cpu ec2 instance and a gpu ec2 instance. The import both work.

**Comment by damirpolat** [comment] 2022-06-07 16:15
> Instead of downgrading `protobuf`. Make sure to update the python toolchains:
> 
> ```python
> pip3 install -U pip
> pip3 install -U setuptools wheel
> ```
> 
> then install autogluon.
> 
> Tested on both a cpu ec2 instance and a gpu ec2 instance. The import both work.

That didn't work for me.

**Comment by sxjscience** [comment] 2022-06-07 16:30
@damirpolat Is it possible for you to help test if the following versions of protobuf will work? This can help us nail down the version cap.

```
pip3 install -U protobuf==3.20.1
pip3 install -U protobuf==3.20.0
pip3 install -U protobuf==3.19.4
pip3 install -U protobuf==3.18.1
```

**Comment by damirpolat** [comment] 2022-06-07 20:23
Only `pip3 install -U protobuf==3.18.1` worked for me.

**Comment by sxjscience** [comment] 2022-06-08 07:13
@yinweisu @gradientsky Do you think if we should limit protobuf to be <=3.18.1. @damirpolat has tried four versions and only 3.18.1 works.

**Comment by yinweisu** [comment] 2022-06-08 16:54
Maybe we can do it to 0.5 release since it's close and this issue seems to happen only on certain environment.

**Comment by andreas12345** [comment] 2022-06-16 11:44
I can reproduce this issue even with protobuf==3.18.1 on two different platforms:

## AL2 on EC2 (CPU)
```
$ uname -a
Linux xxxx 4.14.281-212.502.amzn2.x86_64 #1 SMP Thu May 26 09:52:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
$ python3 --version
Python 3.7.10
$ pip3 install autogluon==0.4.2
$ pip3 install protobuf==3.18.1
$ python3 -c 'from autogluon.text import TextPredictor'
Segmentation fault
$ pip3 freeze
https://paste.debian.net/1244282/
```

## Mac M1:
```
$ uname -a
Darwin xxxxxx 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64
$ python3 --version
Python 3.9.13
$ which python3
/opt/homebrew/bin/python3
$ pip3 install "torch>=1.0,<1.11+cpu" -f https://download.pytorch.org/whl/cpu/torch_stable.html
$ pip3 install autogluon==0.4.2
$ pip3 install protobuf==3.18.1
$ python3 -c 'from autogluon.text import TextPredictor'
libc++abi: terminating with uncaught exception of type std::length_error: vector
Abort trap: 6
$ pip3 freeze
https://paste.debian.net/1244283/
```

**Comment by sxjscience** [comment] 2022-06-16 13:51
@andreas12345 see a similar issue from PyG: https://github.com/pyg-team/pytorch_geometric/issues/4419 .

For M1, the solution is to use venv or anaconda.

**Comment by andreas12345** [comment] 2022-06-16 14:26
Thanks for the pointers!

> pytorch_lightning

On Mac, this triggers the failure (which seems to be randomly sampled from "std::length_error: vector", bad_alloc, and segmentation fault).
```
$ python3
Python 3.9.13 (main, May 24 2022, 21:13:51) 
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytorch_lightning
libc++abi: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
Abort trap: 6
```

> Also, can you try to upgrade pip and try again? pip3 install -U pip, pip3 install -U setuptools wheel

That had no effect on Mac. On Linux, this revealed an exception (AttributeError: module 'distutils' has no attribute 'version') from torch.utils.tensorboard; but after *then* re-installing autogluon, the import works fine. pip3 freeze output now: https://paste.debian.net/1244298/

Thanks!

**Comment by andreas12345** [comment] 2022-06-19 11:57
Getting a segmentation fault with anaconda python as well:
```
$ python -c 'from autogluon.text import pytorch_lightning'
Segmentation fault: 11
```

**Comment by andreas12345** [comment] 2022-06-19 12:15
The segfault can already be triggered with "import torchvision". The only way I could find to prevent it was by installing torch==1.11.0 (which is declared not compatible by autogluon). Is there a reason for requiring <= 1.10, or can we require latest torch version as dependency to avoid this issue?

Thanks!

**Comment by sxjscience** [comment] 2022-06-19 16:10
@andreas12345 See https://github.com/awslabs/autogluon/pull/1836 . We are supporting PT 1.11 there.

**Comment by ddelange** [comment] 2022-06-20 12:33
I'm not sure if lightning transfers the constraints between torchvision/torchaudio/etc and torch into their install_requires. They're noted in code though: https://github.com/Lightning-AI/lightning/blob/0cf9d73d28d9dd0fd419e2a5ee47b7488e5c1883/requirements/adjust-versions.py#L7

And so, because the torchtext/torchaudio/etc libs don't pin torch either, and only mention the compatibility matrix in their respective pypi READMEs, it's currently relatively easy for an end-user to end up with a broken env.

**Comment by sxjscience** [comment] 2022-06-20 20:44
@andreas12345 now the PT 1.11 has been supported via https://github.com/awslabs/autogluon/pull/1836. Feel free to try installing the latest AutoGluon again (clone it and run `full_install.sh`).

**Comment by sxjscience** [comment] 2022-08-24 23:35
The latest installation guide should have resolved the issue. Close it for now.

**Closed by sxjscience** 2022-08-24 23:35 UTC
Labels: bug, urgent, module: text, Needs Triage
