### ISSUE TITLE
Error importing autogluon.vision

### ISSUE THREAD

**Issue by Emekaborisama** [awslabs/autogluon#1185] opened 2021-06-16 17:11 UTC
same error

`ImportError: cannot import name 'stringify' from 'dask.utils' (/usr/local/lib/python3.7/dist-packages/dask/utils.py)`

_Originally posted by @Emekaborisama in https://github.com/awslabs/autogluon/discussions/970#discussioncomment-879402_

**Comment by talhaanwarch** [comment] 2021-06-21 19:25
Can you share your code

**Comment by Innixma** [comment] 2021-06-22 02:47
@Emekaborisama I'd guess your environment is corrupted. Please try with a fresh virtual environment and install following these instructions: https://auto.gluon.ai/stable/install.html

If you are still having issues you'll need to provide more information in order to narrow down the cause.

**Comment by talhaanwarch** [comment] 2021-06-24 08:02
I also faced similar issues caused by dask, and solution is to upgrade pip, wheel and setup

**Comment by Innixma** [comment] 2021-06-27 17:24
Closing this issue for now, please re-open if issues persist after following the install instructions on a fresh venv.

**Closed by Innixma** 2021-06-27 17:24 UTC
