### ISSUE TITLE
Error in google colab

### ISSUE THREAD

**Issue by fryng** [awslabs/autogluon#243] opened 2020-01-24 04:05 UTC
object detection tutorial 在使用google colab时，出现"colab" RuntimeError: There is no current event loop in thread 'IO loop'.
解决方法：
pip install tornado==5.*
pip install -U ipykernel
重启kernel解决!

**Comment by Innixma** [comment] 2020-03-06 22:18
@zhanghang1989 Can you please respond to this issue or mark as resolved if it is outdated?

**Comment by zhanghang1989** [comment] 2020-03-07 00:10
Could you follow the solution here https://github.com/awslabs/autogluon/issues/163#issuecomment-573388784

**Comment by Innixma** [comment] 2020-03-18 02:40
Duplicate of #163. Please follow the solution in #163 to fix, thanks!

**Closed by Innixma** 2020-03-18 02:40 UTC
Labels: duplicate
