### ISSUE TITLE
mxnet_generic_kernel ErrStr:no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by talhaanwarch** [awslabs/autogluon#1270] opened 2021-08-11 12:24 UTC
On google colab, the TextPredictor is not working.

It is throwing the following error
```
MXNetError: Traceback (most recent call last):
  File "../src/ndarray/../operator/tensor/./../mxnet_op.h", line 1121
Name: Check failed: err == cudaSuccess (209 vs. 0) : mxnet_generic_kernel ErrStr:no kernel image is available for execution on the device
```
How to reproduce is as follow
```
!python3 -m pip install -U pip
!python3 -m pip install -U setuptools wheel
!python3 -m pip install -U "mxnet_cu110<2.0.0"
!python3 -m pip install --pre autogluon

from autogluon.core.utils.loaders.load_pd import load
train_data = load('https://autogluon-text.s3-accelerate.amazonaws.com/glue/sst/train.parquet')
test_data = load('https://autogluon-text.s3-accelerate.amazonaws.com/glue/sst/dev.parquet')
subsample_size = 1000  # subsample data for faster demo, try setting this to larger values
train_data = train_data.sample(n=subsample_size, random_state=0)
train_data.head(10)

from autogluon.text import TextPredictor
predictor = TextPredictor(label='label', eval_metric='f1_macro')
predictor.fit(train_data, time_limit=60)
```

Complete logs is as follow
```
INFO:root:NumPy-shape semantics has been activated in your code. This is required for creating and manipulating scalar and zero-size tensors, which were not supported in MXNet before, as in the official NumPy library. Please DO NOT manually deactivate this semantics while using `mxnet.numpy` and `mxnet.numpy_extension` modules.
INFO:autogluon.text.text_prediction.mx.models:The GluonNLP V0 backend is used. We will use 2 cpus and 1 gpus to train each trial.
All Logs will be saved to /content/AutogluonModels/ag-20210811_122158/task0/training.log
INFO:root:Fitting and transforming the train data...
INFO:root:Done! Preprocessor saved to /content/AutogluonModels/ag-20210811_122158/task0/preprocessor.pkl
INFO:root:Process dev set...
INFO:root:Done!
INFO:root:Max length for chunking text: 64, Stochastic chunk: Train-False/Test-False, Test #repeat: 1.
INFO:root:#Total Params/Fixed Params=108990466/0
Level 15:root:Using gradient accumulation. Global batch size = 128
---------------------------------------------------------------------------
MXNetError                                Traceback (most recent call last)
<ipython-input-3-051e78e71d77> in <module>()
      2 
      3 predictor = TextPredictor(label='label', eval_metric='f1_macro')
----> 4 predictor.fit(train_data, time_limit=60)

10 frames
/usr/local/lib/python3.7/dist-packages/autogluon/text/text_prediction/predictor/predictor.py in fit(self, train_data, tuning_data, time_limit, presets, hyperparameters, column_types, num_cpus, num_gpus, num_trials, plot_results, holdout_frac, seed)
    337                               seed=seed,
    338                               plot_results=plot_results,
--> 339                               verbosity=verbosity)
    340         else:
    341             raise NotImplementedError("Currently, we only support using "

/usr/local/lib/python3.7/dist-packages/mxnet/util.py in _with_np_shape(*args, **kwargs)
    295         def _with_np_shape(*args, **kwargs):
    296             with np_shape(active=True):
--> 297                 return func(*args, **kwargs)
    298         return _with_np_shape
    299     else:

/usr/local/lib/python3.7/dist-packages/mxnet/util.py in _with_np_array(*args, **kwargs)
    479         def _with_np_array(*args, **kwargs):
    480             with np_array(active=True):
--> 481                 return func(*args, **kwargs)
    482         return _with_np_array
    483     else:

/usr/local/lib/python3.7/dist-packages/autogluon/text/text_prediction/mx/models.py in train(self, train_data, tuning_data, num_cpus, num_gpus, time_limit, tune_kwargs, search_space, plot_results, console_log, seed, verbosity)
   1024         if scheduler_options['num_trials'] == 1:
   1025             train_fn(train_fn.args['search_space'],
-> 1026                      train_fn.args['_default_config'])
   1027             best_model_saved_dir_path = os.path.join(self._output_directory, 'task0')
   1028             cfg_path = os.path.join(self._output_directory, 'task0', 'cfg.yml')

/usr/local/lib/python3.7/dist-packages/autogluon/core/decorator.py in __call__(self, args, config, **kwargs)
     58             kwargs['reporter'] = FakeReporter()
     59 
---> 60         output = self.f(args, **kwargs)
     61         logger.debug('Reporter Done!')
     62         kwargs['reporter'](done=True)

/usr/local/lib/python3.7/dist-packages/autogluon/core/decorator.py in wrapper_call(*args, **kwargs)
    141         @functools.wraps(func)
    142         def wrapper_call(*args, **kwargs):
--> 143             return func(*args, **kwargs)
    144 
    145         default = kwvars['_default_config']

/usr/local/lib/python3.7/dist-packages/mxnet/util.py in _with_np_shape(*args, **kwargs)
    295         def _with_np_shape(*args, **kwargs):
    296             with np_shape(active=True):
--> 297                 return func(*args, **kwargs)
    298         return _with_np_shape
    299     else:

/usr/local/lib/python3.7/dist-packages/mxnet/util.py in _with_np_array(*args, **kwargs)
    479         def _with_np_array(*args, **kwargs):
    480             with np_array(active=True):
--> 481                 return func(*args, **kwargs)
    482         return _with_np_array
    483     else:

/usr/local/lib/python3.7/dist-packages/autogluon/text/text_prediction/mx/models.py in train_function(args, reporter, train_df_path, tuning_df_path, time_limit, time_start, base_config, problem_type, column_types, feature_columns, label_column, log_metrics, eval_metric, ngpus_per_trial, console_log, seed, verbosity)
    579     best_performance_update_idx = []   # Stores the update index that reached the best validation performance
    580     best_score = None
--> 581     mx.npx.waitall()
    582     no_better_rounds = 0
    583     report_idx = 0

/usr/local/lib/python3.7/dist-packages/mxnet/ndarray/ndarray.py in waitall()
    209        If your mxnet code throws an exception, then waitall can cause performance impact.
    210     """
--> 211     check_call(_LIB.MXNDArrayWaitAll())
    212 
    213 

/usr/local/lib/python3.7/dist-packages/mxnet/base.py in check_call(ret)
    244     """
    245     if ret != 0:
--> 246         raise get_last_ffi_error()
    247 
    248 
```

**Comment by Innixma** [comment] 2021-08-11 19:26
I was able to run the code without issue: https://colab.research.google.com/drive/1HrEbSEnRsM0uh8fupWhsqLZXYRt04eBI?usp=sharing

Did you make sure to use a Colab Notebook with GPU enabled?

**Comment by talhaanwarch** [comment] 2021-08-11 21:59
I think i have enabled gpu,and If you check the logs say We will use 2 cpus and 1 gpus to train each trial. But I will check it again as it's working on your side

**Comment by talhaanwarch** [comment] 2021-08-12 04:35
i am not sure, why i am getting this error, but now I am not getting, but I would recommend to check the logs in above message

**Comment by Innixma** [comment] 2021-08-14 00:24
Thanks for double checking! Since we can't reproduce the issue anymore, I will close this issue for now. Please re-open if the issue appears again and provide a reproducible colab notebook for debugging.

**Closed by Innixma** 2021-08-14 00:24 UTC
Labels: gpu
