### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by cpoptic** [awslabs/autogluon#1043] opened 2021-03-31 19:10 UTC
When running TabularPredictor.fit(), I encounter a BrokenPipeError for some reason.
What is causing this?
Could it be due to OOM error?

> Fitting model: XGBoost ...
> 	-34.1179	 = Validation root_mean_squared_error score
> 	10.58s	 = Training runtime
> 	0.03s	 = Validation runtime
> Fitting model: NeuralNetMXNet ...
> 	-34.2849	 = Validation root_mean_squared_error score
> 	43.63s	 = Training runtime
> 	0.1s	 = Validation runtime
> Fitting model: NeuralNetFastAI ...
> 	-76.3191	 = Validation root_mean_squared_error score
> 	18.02s	 = Training runtime
> 	0.27s	 = Validation runtime
> Fitting model: LightGBMLarge ...
> 	-33.4557	 = Validation root_mean_squared_error score
> 	18.32s	 = Training runtime
> 	0.04s	 = Validation runtime
> ---------------------------------------------------------------------------
> BrokenPipeError                           Traceback (most recent call last)
> <ipython-input-54-00f3a4482ed7> in <module>
>       3 # from https://auto.gluon.ai/stable/index.html
>       4 # 
> ----> 5 predictor = TabularPredictor(label=DEPENDENT_VARIABLE).fit(train_data=train_data)
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\autogluon\core\utils\decorators.py in _call(*args, **kwargs)
>      27         def _call(*args, **kwargs):
>      28             gargs, gkwargs = g(*other_args, *args, **kwargs)
> ---> 29             return f(*gargs, **gkwargs)
>      30         return _call
>      31     return _unpack_inner
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\autogluon\tabular\predictor\predictor.py in fit(self, train_data, tuning_data, time_limit, presets, hyperparameters, feature_metadata, **kwargs)
>     689         self._learner.fit(X=train_data, X_val=tuning_data, X_unlabeled=unlabeled_data,
>     690                           holdout_frac=holdout_frac, num_bag_folds=num_bag_folds, num_bag_sets=num_bag_sets, num_stack_levels=num_stack_levels,
> --> 691                           hyperparameters=hyperparameters, core_kwargs=core_kwargs, time_limit=time_limit, verbosity=verbosity)
>     692         self._set_post_fit_vars()
>     693 
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\autogluon\tabular\learner\abstract_learner.py in fit(self, X, X_val, **kwargs)
>     124             raise AssertionError('Learner is already fit.')
>     125         self._validate_fit_input(X=X, X_val=X_val, **kwargs)
> --> 126         return self._fit(X=X, X_val=X_val, **kwargs)
>     127 
>     128     def _fit(self, X: DataFrame, X_val: DataFrame = None, scheduler_options=None, hyperparameter_tune=False,
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\autogluon\tabular\learner\default_learner.py in _fit(self, X, X_val, X_unlabeled, holdout_frac, num_bag_folds, num_bag_sets, time_limit, verbosity, **trainer_fit_kwargs)
>      93 
>      94         self.save()
> ---> 95         trainer.fit(X, y, X_val=X_val, y_val=y_val, X_unlabeled=X_unlabeled, holdout_frac=holdout_frac, time_limit=time_limit_trainer, **trainer_fit_kwargs)
>      96         self.save_trainer(trainer=trainer)
>      97         time_end = time.time()
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\autogluon\tabular\trainer\auto_trainer.py in fit(self, X, y, hyperparameters, X_val, y_val, X_unlabeled, feature_prune, holdout_frac, num_stack_levels, core_kwargs, time_limit, **kwargs)
>      50         self._train_multi_and_ensemble(X, y, X_val, y_val, X_unlabeled=X_unlabeled, hyperparameters=hyperparameters,
>      51                                        feature_prune=feature_prune,
> ---> 52                                        num_stack_levels=num_stack_levels, time_limit=time_limit, core_kwargs=core_kwargs)
>      53 
>      54     def get_models_distillation(self, hyperparameters, **kwargs):
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\autogluon\tabular\trainer\abstract_trainer.py in _train_multi_and_ensemble(self, X, y, X_val, y_val, hyperparameters, X_unlabeled, num_stack_levels, time_limit, **kwargs)
>    1290         self._num_cols_train = len(list(X.columns))
>    1291         model_names_fit = self.train_multi_levels(X, y, hyperparameters=hyperparameters, X_val=X_val, y_val=y_val,
> -> 1292                                                   X_unlabeled=X_unlabeled, level_start=1, level_end=num_stack_levels+1, time_limit=time_limit, **kwargs)
>    1293         if len(self.get_model_names()) == 0:
>    1294             raise ValueError('AutoGluon did not successfully train any models')
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\autogluon\tabular\trainer\abstract_trainer.py in train_multi_levels(self, X, y, hyperparameters, X_val, y_val, X_unlabeled, base_model_names, feature_prune, core_kwargs, aux_kwargs, level_start, level_end, time_limit, name_suffix, relative_stack)
>     259                 models=hyperparameters, level=level, base_model_names=base_model_names,
>     260                 feature_prune=feature_prune,
> --> 261                 core_kwargs=core_kwargs_level, aux_kwargs=aux_kwargs_level, name_suffix=name_suffix,
>     262             )
>     263             model_names_fit += base_model_names + aux_models
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\autogluon\tabular\trainer\abstract_trainer.py in stack_new_level(self, X, y, models, X_val, y_val, X_unlabeled, level, base_model_names, feature_prune, core_kwargs, aux_kwargs, name_suffix)
>     290             aux_models = self.stack_new_level_aux(X=X, y=y, base_model_names=core_models, level=level+1, **aux_kwargs)
>     291         else:
> --> 292             aux_models = self.stack_new_level_aux(X=X_val, y=y_val, fit=False, base_model_names=core_models, level=level+1, **aux_kwargs)
>     293         return core_models, aux_models
>     294 
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\autogluon\tabular\trainer\abstract_trainer.py in stack_new_level_aux(self, X, y, base_model_names, level, fit, stack_name, time_limit, name_suffix, get_models_func, check_if_best)
>     367         Auxiliary models never use the original features and only train with the predictions of other models as features.
>     368         """
> --> 369         X_stack_preds = self.get_inputs_to_stacker(X, base_models=base_model_names, fit=fit, use_orig_features=False)
>     370         if self.weight_evaluation:
>     371             X, w = extract_column(X, self.sample_weight)  # TODO: consider redesign with w as separate arg instead of bundled inside X
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\autogluon\tabular\trainer\abstract_trainer.py in get_inputs_to_stacker(self, X, base_models, model_pred_proba_dict, fit, use_orig_features)
>     503             base_models = []
>     504         if not fit:
> --> 505             model_pred_proba_dict = self.get_model_pred_proba_dict(X=X, models=base_models, model_pred_proba_dict=model_pred_proba_dict)
>     506             model_pred_proba_list = [model_pred_proba_dict[model] for model in base_models]
>     507         else:
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\autogluon\tabular\trainer\abstract_trainer.py in get_model_pred_proba_dict(self, X, models, model_pred_proba_dict, model_pred_time_dict, fit, record_pred_time)
>     487                     model_pred_proba_dict[model_name] = model.predict_proba(X, **preprocess_kwargs)
>     488                 else:
> --> 489                     model_pred_proba_dict[model_name] = model.predict_proba(X)
>     490 
>     491             if record_pred_time:
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\autogluon\core\models\abstract\abstract_model.py in predict_proba(self, X, normalize, **kwargs)
>     456         if normalize is None:
>     457             normalize = self.normalize_pred_probas
> --> 458         y_pred_proba = self._predict_proba(X=X, **kwargs)
>     459         if normalize:
>     460             y_pred_proba = normalize_pred_probas(y_pred_proba, self.problem_type)
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\autogluon\tabular\models\fastainn\tabular_nn_fastai.py in _predict_proba(self, X, **kwargs)
>     351             X, cat_names=self.cat_columns.copy(), cont_names=self.cont_columns.copy(), procs=self.procs))
>     352         with progress_disabled_ctx(self.model) as model:
> --> 353             preds, _ = model.get_preds(ds_type=DatasetType.Test)
>     354         if single_row:
>     355             preds = preds[:1, :]
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\fastai\basic_train.py in get_preds(self, ds_type, activ, with_loss, n_batch, pbar)
>     339         callbacks = [cb(self) for cb in self.callback_fns + listify(defaults.extra_callback_fns)] + listify(self.callbacks)
>     340         return get_preds(self.model, self.dl(ds_type), cb_handler=CallbackHandler(callbacks),
> --> 341                          activ=activ, loss_func=lf, n_batch=n_batch, pbar=pbar)
>     342 
>     343     def pred_batch(self, ds_type:DatasetType=DatasetType.Valid, batch:Tuple=None, reconstruct:bool=False,
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\fastai\basic_train.py in get_preds(model, dl, pbar, cb_handler, activ, loss_func, n_batch)
>      42     "Tuple of predictions and targets, and optional losses (if `loss_func`) using `dl`, max batches `n_batch`."
>      43     res = [to_float(torch.cat(o).cpu()) for o in
> ---> 44            zip(*validate(model, dl, cb_handler=cb_handler, pbar=pbar, average=False, n_batch=n_batch))]
>      45     if loss_func is not None:
>      46         with NoneReduceOnCPU(loss_func) as lf: res.append(lf(res[0], res[1]))
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\fastai\basic_train.py in validate(model, dl, loss_func, cb_handler, pbar, average, n_batch)
>      55         val_losses,nums = [],[]
>      56         if cb_handler: cb_handler.set_dl(dl)
> ---> 57         for xb,yb in progress_bar(dl, parent=pbar, leave=(pbar is not None)):
>      58             if cb_handler: xb, yb = cb_handler.on_batch_begin(xb, yb, train=False)
>      59             val_loss = loss_batch(model, xb, yb, loss_func, cb_handler=cb_handler)
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\fastprogress\fastprogress.py in __iter__(self)
>      45         except Exception as e:
>      46             self.on_interrupt()
> ---> 47             raise e
>      48 
>      49     def update(self, val):
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\fastprogress\fastprogress.py in __iter__(self)
>      39         if self.total != 0: self.update(0)
>      40         try:
> ---> 41             for i,o in enumerate(self.gen):
>      42                 if i >= self.total: break
>      43                 yield o
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\fastai\basic_data.py in __iter__(self)
>      73     def __iter__(self):
>      74         "Process and returns items from `DataLoader`."
> ---> 75         for b in self.dl: yield self.proc_batch(b)
>      76 
>      77     @classmethod
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\torch\utils\data\dataloader.py in __iter__(self)
>     353             return self._iterator
>     354         else:
> --> 355             return self._get_iterator()
>     356 
>     357     @property
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\torch\utils\data\dataloader.py in _get_iterator(self)
>     299         else:
>     300             self.check_worker_number_rationality()
> --> 301             return _MultiProcessingDataLoaderIter(self)
>     302 
>     303     @property
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\site-packages\torch\utils\data\dataloader.py in __init__(self, loader)
>     912             #     before it starts, and __del__ tries to join but will get:
>     913             #     AssertionError: can only join a started process.
> --> 914             w.start()
>     915             self._index_queues.append(index_queue)
>     916             self._workers.append(w)
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\multiprocessing\process.py in start(self)
>     110                'daemonic processes are not allowed to have children'
>     111         _cleanup()
> --> 112         self._popen = self._Popen(self)
>     113         self._sentinel = self._popen.sentinel
>     114         # Avoid a refcycle if the target function holds an indirect
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\multiprocessing\context.py in _Popen(process_obj)
>     221     @staticmethod
>     222     def _Popen(process_obj):
> --> 223         return _default_context.get_context().Process._Popen(process_obj)
>     224 
>     225 class DefaultContext(BaseContext):
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\multiprocessing\context.py in _Popen(process_obj)
>     320         def _Popen(process_obj):
>     321             from .popen_spawn_win32 import Popen
> --> 322             return Popen(process_obj)
>     323 
>     324     class SpawnContext(BaseContext):
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\multiprocessing\popen_spawn_win32.py in __init__(self, process_obj)
>      87             try:
>      88                 reduction.dump(prep_data, to_child)
> ---> 89                 reduction.dump(process_obj, to_child)
>      90             finally:
>      91                 set_spawning_popen(None)
> 
> C:\ProgramData\Anaconda3\envs\my_project\lib\multiprocessing\reduction.py in dump(obj, file, protocol)
>      58 def dump(obj, file, protocol=None):
>      59     '''Replacement for pickle.dump() using ForkingPickler.'''
> ---> 60     ForkingPickler(file, protocol).dump(obj)
>      61 
>      62 #
> 
> BrokenPipeError: [Errno 32] Broken pipe

**Comment by Innixma** [comment] 2021-03-31 19:45
Thanks for submitting an issue! Please also include more information such as Python version and OS (I assume Windows).

This appears to be an issue related to Windows interaction with torch/fastai. If you can isolate the issue to a minimal example such as with `hyperparameters=['FASTAI': {}]`, this would be helpful.

If you want to avoid the error for now, you can disable the FASTAI model via `excluded_model_types=['FASTAI']`.

We currently don't have easy access to windows machines to test, so if anyone wants to try debugging and fixing this, that would be excellent.

**Comment by cpoptic** [comment] 2021-04-01 00:45
Thanks @Innixma , yep it's a Windows 10 machine on VS Code (I really need to set up WSL on VS Code so I can run this code on Linux).
python -V is `3.7.10`, running in a Conda environment.

I suspect you're right about the `fastai` on Windows issue.

I don't know how to check the logs (if there are any), but it appears AutoGluon runs successfully in this order:

1. RandomForestMSE 
2. ExtraTreesMSE 
3. KNeighborsUnif 
4. KNeighborsDist 
5. LightGBM 
6. LightGBMXT 
7. CatBoost 
8. XGboost
9. NeuralNetMXNet 
10. NeuralNetFastAI 
11. LightGBMLarge 

and then it crashes after LightGBMLarge.  Unfortunately, I'm not sure which model gets trained after that one, but I'm guessing that would be the one it fails on.

Will try re-running with your reco of `excluded_model_types=['FASTAI']` and let you know of the results.

**Comment by VGODIE** [comment] 2021-04-05 09:07
I have the same error on MacOs

**Comment by Innixma** [comment] 2022-01-12 19:49
Closing for now as this may have been resolved since refactors for v0.4.

Please re-open and provide a reproducible script if the issue persists.

**Closed by Innixma** 2022-01-12 19:49 UTC
Labels: bug, help wanted, good first issue, Windows OS, tabular, MacOS
