### ISSUE TITLE
why continue training after the max trial reached?

### ISSUE THREAD

**Issue by Fanxingye** [awslabs/autogluon#1192] opened 2021-06-19 06:58 UTC
I set num_trials to be 15, training starts from trial_0 to trial_14, but when trial_14 was finished, it continue to run trial_0. This happend on two different tasks. Why it happend?

**Comment by Innixma** [comment] 2021-06-22 02:43
Could you provide a minimally reproducible example + log output? I'm assuming you are referring to ImagePredictor.

**Comment by Fanxingye** [comment] 2021-06-22 09:46
My task is image classification and hpo was used. This is the log:
![image](https://user-images.githubusercontent.com/50837470/122903087-a8226380-d381-11eb-83bb-8f230075ea6f.png)

**Comment by zhreshold** [comment] 2021-06-23 00:24
I believe the last trial 0 is the final run, it will load the best config from trial 0-14 and perform the training with combined train/valid data

**Comment by jianzhnie** [comment] 2021-06-23 03:27
@Innixma @zhreshold  I agree that it should be clearer in the logs, and write the final trail results into .trial instate of overwriting the .trail_0

**Comment by Fanxingye** [comment] 2021-06-23 08:50
@zhreshold How autogluon calculate valid_acc at the last trial_0 when train/valid data were combined?

**Comment by jianzhnie** [comment] 2021-07-02 03:54
> I believe the last trial 0 is the final run, it will load the best config from trial 0-14 and perform the training with combined train/valid data

I checked the code, it dose load the best config from trial, but dose not training with the combined train/val data

**Comment by Innixma** [comment] 2021-08-18 21:24
This issue has been fixed in #1282, and because of it, model quality will be greatly improved in general when HPO is enabled as prior it was re-training the best model config but running out of time, causing the model to be quite bad in many cases.

**Closed by Innixma** 2021-08-18 21:24 UTC
Labels: bug, urgent, vision
