### ISSUE TITLE
[BUG]predict_proba() and predict() doesn't work for Torch tensor inference with batch size larger than 1

### ISSUE THREAD

**Issue by ChengeLi** [awslabs/autogluon#1890] opened 2022-06-24 00:17 UTC
- [x] I have checked that this bug exists on the latest stable version of AutoGluon
- [ ] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**
When using torch tensor (not pandas dataframe) as data format during inference, we found that the predict_proba() function will have errors when the batch size is larger than 1. The list of prediction is a flattened list instead of list of lists, and [this assignment](https://github.com/awslabs/autogluon/blob/master/vision/src/autogluon/vision/predictor/predictor.py#L546) will have errors. 

`ValueError: Columns must be same length as key`

**Expected behavior**
It should return a list of confidence scores with different class as different columns. 

**To Reproduce**

```
from PIL import Image
import torchvision.transforms as transforms
import math 
import torch


crop_pct = 0.99
img_size = 224
preprocess = transforms.Compose([
                                transforms.Resize(int(math.floor(img_size / crop_pct))),
                                transforms.CenterCrop(img_size),
                                transforms.ToTensor(),
                                transforms.Normalize(
                                    mean=[0.485, 0.456, 0.406], 
                                    std=[0.229, 0.224, 0.225]),
                                ]
                                 )
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def predict_using_torch_tensor(model, img_files):
    batch_decoded = preprocess(Image.open(img_files[0])).unsqueeze(0)
    for img_file in img_files[1:]:
        current_img_tensor = preprocess(Image.open(img_file)).unsqueeze(0)
        batch_decoded = torch.cat((batch_decoded, current_img_tensor), 0)
    print(batch_decoded.shape)
    batch_decoded = batch_decoded.to(device)
    pred_proba = model.predict_proba(batch_decoded)
#     pred_proba = model.predict(batch_decoded)
    return pred_proba


### one-by-one inference is working
for ind in range(10):
    pred_proba = predict_using_torch_tensor(my_model, [image_list[ind]])
    print('{}'.format(np.array(pred_proba)))

### batch inference is not working
pred_proba = predict_using_torch_tensor(my_model, image_list[:10])
print('{}'.format(np.array(pred_proba)))

```

**Screenshots**
![batch_inference_bug_autogluon](https://user-images.githubusercontent.com/8276766/175435692-14896211-5ac9-4b9c-8eab-35f7c1bf575a.png)

**Installed Versions**
Which version of AutoGluon are you are using?  
I'm using Autogluon 0.4.2.

**Comment by bryanyzhu** [comment] 2022-06-26 03:24
Hi @ChengeLi , the PR #1896 to fix this problem has been merged, can you give the master branch a try to see if the issue is resolved? Thank you.

**Comment by bryanyzhu** [comment] 2022-06-30 22:19
@ChengeLi Just to check if the issue has been resolved, thanks.

**Comment by ChengeLi** [comment] 2022-07-01 08:48
hi @bryanyzhu, Thanks for the quick fix! The PR resolved the problem. 
Forgot to mention in the original issue description, the function predict() also couldn't handle torch tensor with batch size >1. It only returns the predicted class index for the 1st sample instead of for the whole batch, without error message. Could you also take a look? Thanks!

**Comment by bryanyzhu** [comment] 2022-07-01 18:02
Sure @ChengeLi . Since this issue has been resolved, and the PR has been merged. Can you open a new issue? I will close this one for now.

**Closed by bryanyzhu** 2022-07-01 18:02 UTC
Labels: bug: unconfirmed, Needs Triage
