### ISSUE TITLE
Segmentation fault in RandomForestMSE

### ISSUE THREAD

**Issue by albert-ying** [awslabs/autogluon#1220] opened 2021-07-01 06:14 UTC
Hi, I encountered a weird segmentation fault when running RandomForestMSE model.

```
predictor = TabularPredictor(label='lab', path='result')
predictor.fit(train_data=df_train.sample(500), tuning_data=df_val.sample(100), use_bag_holdout=True, hyperparameters=hyperparameters)
```

```
Fitting model: RandomForestMSE ...
Segmentation fault
```

It should not be a memory issue as I only sampled 500 row of the training data.

I also tried to set the hyperparameters to:

```
'RF': [
	{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}, 'n_jobs': 16},
	{'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}, 'n_jobs': 16},
	{'criterion': 'mse', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression']}, 'n_jobs': 16},
],
```

But it doesn't help.

**Comment by Innixma** [comment] 2021-07-01 20:59
Thanks for reporting this issue! I am not able to trivially reproduce as it seems to work for me. Could you provide a reproducible script or reproduce the issue on a colab notebook and share the notebook?

**Comment by albert-ying** [comment] 2021-07-01 21:30
It seems to be related to the system. It works for me after I switched to another server.

## This is the system where I see the error
```
NAME="Ubuntu"
VERSION="14.04.6 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.6 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

**Comment by Innixma** [comment] 2021-07-01 23:43
Thanks for the info! I'll close this for now as it is quite difficult to debug the cause and it seems like a niche error.

If anyone experiences a similar issue, please re-open the ticket.

**Closed by Innixma** 2021-07-01 23:43 UTC
Labels: bug: unconfirmed, tabular
