### ISSUE TITLE
ImagePredictor crashes when using multiple GPU

### ISSUE THREAD

**Issue by lzcemma** [awslabs/autogluon#1237] opened 2021-07-15 21:44 UTC
Trained a ImagePredictor by calling TabularPredictor.fit(). Model checkedpoint has been successfully saved. 
I try to call predictor.leaderboard, and got following error. I was using 8 GPU. However, it works when I specify only one gpu with CUDA_VISIBLE_DEIVICES.

**Error Message:**
test_leaderboard = predictor.leaderboard(test_df)
  File "/mnt/efs/fs1/autogluon/tabular/src/autogluon/tabular/predictor/predictor.py", line 1086, in leaderboard
    only_pareto_frontier=only_pareto_frontier, silent=silent)
  File "/mnt/efs/fs1/autogluon/tabular/src/autogluon/tabular/learner/abstract_learner.py", line 620, in leaderboard
    leaderboard = self.score_debug(X=X, y=y, extra_info=extra_info, extra_metrics=extra_metrics, silent=True)
  File "/mnt/efs/fs1/autogluon/tabular/src/autogluon/tabular/learner/abstract_learner.py", line 302, in score_debug
    model_pred_proba_dict, pred_time_test_marginal = trainer.get_model_pred_proba_dict(X=X, models=all_trained_models_can_infer, fit=False, record_pred_time=True)
  File "/mnt/efs/fs1/autogluon/tabular/src/autogluon/tabular/trainer/abstract_trainer.py", line 508, in get_model_pred_proba_dict
    model_pred_proba_dict[model_name] = model.predict_proba(X)
  File "/mnt/efs/fs1/autogluon/core/src/autogluon/core/models/abstract/abstract_model.py", line 546, in predict_proba
    y_pred_proba = self._predict_proba(X=X, **kwargs)
  File "/mnt/efs/fs1/autogluon/tabular/src/autogluon/tabular/models/image_prediction/image_predictor.py", line 139, in _predict_proba
    y_pred_proba = self.model.predict_proba(X, as_pandas=False)
  File "/mnt/efs/fs1/autogluon/vision/src/autogluon/vision/predictor/predictor.py", line 494, in predict_proba
    y_pred_proba = self._classifier.predict(data, with_proba=True)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/gluoncv/auto/estimators/base_estimator.py", line 199, in predict
    return self._predict(x, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/gluoncv/auto/estimators/image_classification/image_classification.py", line 507, in _predict
    return self._predict_proba(x, ctx_id=ctx_id)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/gluoncv/auto/estimators/image_classification/image_classification.py", line 613, in _predict_proba
    df = self._predict_proba(tuple(x['image']))
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/gluoncv/auto/estimators/image_classification/image_classification.py", line 623, in _predict_proba
    batch = mx.gluon.utils.split_and_load(batch, ctx_list=self.ctx, even_split=False)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/mxnet/gluon/utils.py", line 119, in split_and_load
    return [i.as_in_context(ctx) for i, ctx in zip(slices, ctx_list)]
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/mxnet/gluon/utils.py", line 119, in <listcomp>
    return [i.as_in_context(ctx) for i, ctx in zip(slices, ctx_list)]
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py", line 2799, in as_in_context
    return self.copyto(context)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py", line 2666, in copyto
    return _internal._copyto(self, out=hret)
  File "<string>", line 27, in _copyto
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/mxnet/_ctypes/ndarray.py", line 91, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/mxnet/base.py", line 246, in check_call
    raise get_last_ffi_error()
mxnet.base.MXNetError: Traceback (most recent call last):
  File "../src/imperative/./imperative_utils.h", line 147
MXNetError: Operator _copyto inferring shapes failed.
input shapes:
[-1,3,224,224]
output shapes:
[-1,3,224,224]
operator attributes:

**Comment by Innixma** [comment] 2021-07-20 21:06
Thanks for reporting! @zhreshold we probably don't need to fix in MXNet version since we are migrating to TIMM, but we should make sure that post-migration we can handle multiple GPU training/inference.

**Comment by yinweisu** [comment] 2022-01-12 21:04
Close this issue as it should be solved after switching backend to torch. Has verified training/inference works with multiple GPU. Please re-open if there's still issue and consider providing a minimal reproducible code

**Closed by yinweisu** 2022-01-12 21:04 UTC
Labels: bug, vision
