### ISSUE TITLE
[BUG] 'NoneType' object has no attribute 'copy' when TextPredictor.evaluate

### ISSUE THREAD

**Issue by Wang-Lin-boop** [awslabs/autogluon#1686] opened 2022-05-01 01:10 UTC
When I tried to run my own data using the code in the sentence similarity tutorial, it returned an error when I performed the test.

**Code**
```python
import pandas as pd
import sys
import numpy as np
import warnings
warnings.filterwarnings('ignore')
np.random.seed(123)
from autogluon.text import TextPredictor
import torch
print(torch.cuda.is_available())  # Should be True
print(torch.cuda.device_count())  # Should be > 0

test_data_csv=sys.argv[1]
job_name=sys.argv[2]
sts_test_data = pd.read_csv(test_data_csv)

predictor_sts = TextPredictor(label='score', path=job_name)
predictor_sts.load(path=job_name)
test_score = predictor_sts.evaluate(sts_test_data, metrics=['rmse', 'pearsonr', 'spearmanr'])
print('RMSE = {:.2f}'.format(test_score['rmse']))
print('PEARSONR = {:.4f}'.format(test_score['pearsonr']))
print('SPEARMANR = {:.4f}'.format(test_score['spearmanr']))
```
The error occurs when I want to use the trained model to make evaluation.

**Error**
```
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    test_score = predictor_sts.evaluate(sts_test_data, metrics=['rmse', 'pearsonr', 'spearmanr'])
  File "/home/bailab/software/anaconda3/envs/autogluon/lib/python3.8/site-packages/autogluon/text/text_prediction/predictor.py", line 287, in evaluate
    return self._predictor.evaluate(
  File "/home/bailab/software/anaconda3/envs/autogluon/lib/python3.8/site-packages/autogluon/text/automm/predictor.py", line 720, in evaluate
    logits = self._predict(
  File "/home/bailab/software/anaconda3/envs/autogluon/lib/python3.8/site-packages/autogluon/text/automm/predictor.py", line 595, in _predict
    data_processors = self._data_processors.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

**Installed Versions**
```
INSTALLED VERSIONS
------------------
date                 : 2022-05-01
time                 : 09:06:29.828473
python               : 3.8.0.final.0
OS                   : Linux
OS-release           : 5.4.0-107-generic
Version              : #121~18.04.1-Ubuntu SMP Thu Mar 24 17:21:33 UTC 2022
machine              : x86_64
processor            : x86_64
num_cores            : 64
cpu_ram_mb           : 47973
cuda version         : 11.460.91.03
num_gpus             : 1
gpu_ram_mb           : [4942]
avail_disk_size_mb   : 277883

autogluon.common     : 0.4.0
autogluon.core       : 0.4.0
autogluon.features   : 0.4.0
autogluon.tabular    : 0.4.0
autogluon.text       : 0.4.0
autogluon.vision     : 0.4.0
autogluon_contrib_nlp: None
boto3                : 1.22.1
catboost             : 1.0.5
dask                 : 2021.11.2
distributed          : 2021.11.2
fairscale            : 0.4.6
fastai               : 2.5.6
gluoncv              : 0.11.0
lightgbm             : 3.3.2
matplotlib           : 3.5.1
networkx             : 2.8
nptyping             : 1.4.4
numpy                : 1.22.3
omegaconf            : 2.1.2
pandas               : 1.3.5
PIL                  : 9.0.1
psutil               : 5.8.0
pytorch_lightning    : 1.5.10
ray                  : 1.8.0
requests             : 2.27.1
scipy                : 1.7.3
sentencepiece        : None
skimage              : 0.19.2
sklearn              : 1.0.2
smart_open           : 5.2.1
timm                 : 0.5.4
torch                : 1.10.2+cu102
torchmetrics         : 0.7.3
tqdm                 : 4.64.0
transformers         : 4.16.2
xgboost              : 1.4.2
```

**Comment by sxjscience** [comment] 2022-05-03 14:13
Would you install the prerelease version and try again?
`python3 -m pip install --pre autogluon`. We previously fixed an issue about loading a saved checkpoint on a different instance. Also, how’s the model trained?

**Comment by Wang-Lin-boop** [comment] 2022-05-03 14:21
Thank you for your help!
>Would you install the prerelease version and try again?

Do I need to retrain the model to try again with the method you mentioned?
>Also, how’s the model trained?

The model was trained using TextPredictor with the following code.
```python
import pandas as pd
import sys
import numpy as np
import warnings
import matplotlib.pyplot as plt
warnings.filterwarnings('ignore')
np.random.seed(123)
from autogluon.text import TextPredictor
import torch
print(torch.cuda.is_available())  # Should be True
print(torch.cuda.device_count())  # Should be > 0

train_data_csv=sys.argv[1]
job_name=sys.argv[2]
pretrained_model=None
training_preset=sys.argv[3]
sts_train_data = pd.read_csv(train_data_csv)

print('Min score=', min(sts_train_data['score']), ', Max score=', max(sts_train_data['score']))

predictor_sts = TextPredictor(label='score', path=job_name)
if pretrained_model is None:
    print("Start a now job: ",job_name)
else:
    predictor_sts.load(path=pretrained_model)
predictor_sts.fit(sts_train_data, num_cpus=20, column_types = {"smiles1": "text", "smiles2": "text", "score": "numerical"}, presets=training_preset)

predictor_sts.fit_summary(show_plot=True)

```

**Comment by sxjscience** [comment] 2022-05-03 14:22
There is no need to retrain if the model has been trained via 0.4.0. We design it in a way that it will automatically upgrade the checkpoints. You can directly call .load()

**Comment by sxjscience** [comment] 2022-05-03 14:23
We also tested for it in https://github.com/awslabs/autogluon/blob/e66ebc40bb50108f768e83892d0b3a8181e264cc/text/tests/unittests/automm/test_backward_compatibility.py#L12

**Comment by Wang-Lin-boop** [comment] 2022-05-03 14:38
After I updated the version, a new error appeared.
```
Load pretrained checkpoint: deepshape_3/model.ckpt
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    test_score = predictor_sts.evaluate(sts_test_data, metrics=['rmse', 'pearsonr', 'spearmanr'])
  File "/home/bailab/software/anaconda3/envs/autogluon/lib/python3.8/site-packages/autogluon/text/text_prediction/predictor.py", line 286, in evaluate
    return self._predictor.evaluate(
  File "/home/bailab/software/anaconda3/envs/autogluon/lib/python3.8/site-packages/autogluon/text/automm/predictor.py", line 986, in evaluate
    logits = self._predict(
  File "/home/bailab/software/anaconda3/envs/autogluon/lib/python3.8/site-packages/autogluon/text/automm/predictor.py", line 869, in _predict
    if isinstance(self._config.env.num_gpus, int)
AttributeError: 'NoneType' object has no attribute 'env'
```

**Comment by sxjscience** [comment] 2022-05-03 14:41
This is weird. Would you try retraining with the latest version? We haven’t seen such an error in our development before. Another way is to share the checkpoint with us and we may help take a look.

**Comment by Wang-Lin-boop** [comment] 2022-05-03 14:47
Yes, I will try to retrain, thanks for your help. Can I send the checkpoint file to you by email?

**Comment by Wang-Lin-boop** [comment] 2022-05-03 14:49
BTW, is it possible that this reported error is not a problem of load()? I can successfully load the model and continue training.

**Comment by sxjscience** [comment] 2022-05-03 14:57
My email is xshiab AT connect DOT ust DOT hk

**Comment by Wang-Lin-boop** [comment] 2022-05-04 01:30
It reports an same error using the retrained model. 
```
Load pretrained checkpoint: deepshape_4/model.ckpt
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    test_score = predictor_sts.evaluate(sts_test_data, metrics=['rmse', 'pearsonr', 'spearmanr'])
  File "/home/bailab/software/anaconda3/envs/autogluon/lib/python3.8/site-packages/autogluon/text/text_prediction/predictor.py", line 286, in evaluate
    return self._predictor.evaluate(
  File "/home/bailab/software/anaconda3/envs/autogluon/lib/python3.8/site-packages/autogluon/text/automm/predictor.py", line 986, in evaluate
    logits = self._predict(
  File "/home/bailab/software/anaconda3/envs/autogluon/lib/python3.8/site-packages/autogluon/text/automm/predictor.py", line 869, in _predict
    if isinstance(self._config.env.num_gpus, int)
AttributeError: 'NoneType' object has no attribute 'env'
```

**Comment by sxjscience** [comment] 2022-05-04 01:50
Just want to confirm. Would you rerun the diagnosis command and check the version of AutoGluon? Actually, we are auto-generating document page and haven’t seen such issue (e.g. https://auto.gluon.ai/dev/index.html ) Meanwhile, I’ve received the checkpoint and will debug locally this evening.

**Comment by Wang-Lin-boop** [comment] 2022-05-04 04:23
Yes, I had rechecked the version. In fact, the only way to reinstall the pre version is to uninstall it with pip uninstall first.
```python
>>> from autogluon.core.utils import show_versions
>>> show_versions()

INSTALLED VERSIONS
------------------
date                 : 2022-05-04
time                 : 12:22:49.577468
python               : 3.8.0.final.0
OS                   : Linux
OS-release           : 5.4.0-107-generic
Version              : #121~18.04.1-Ubuntu SMP Thu Mar 24 17:21:33 UTC 2022
machine              : x86_64
processor            : x86_64
num_cores            : 64
cpu_ram_mb           : 47973
cuda version         : 11.460.91.03
num_gpus             : 1
gpu_ram_mb           : [7788]
avail_disk_size_mb   : 283689

autogluon.common     : 0.4.1b20220503
autogluon.core       : 0.4.1b20220503
autogluon.features   : 0.4.1b20220503
autogluon.tabular    : 0.4.1b20220503
autogluon.text       : 0.4.1b20220503
autogluon.vision     : 0.4.1b20220503
autogluon_contrib_nlp: None
boto3                : 1.22.1
catboost             : 1.0.5
dask                 : 2021.11.2
distributed          : 2021.11.2
fairscale            : 0.4.6
fastai               : 2.5.6
gluoncv              : 0.11.0
lightgbm             : 3.3.2
matplotlib           : 3.5.1
networkx             : 2.8
nptyping             : 1.4.4
numpy                : 1.22.3
omegaconf            : 2.1.2
pandas               : 1.3.5
PIL                  : 9.0.1
psutil               : 5.8.0
pytorch_lightning    : 1.5.10
ray                  : 1.10.0
requests             : 2.27.1
scipy                : 1.7.3
sentencepiece        : None
skimage              : 0.19.2
sklearn              : 1.0.2
smart_open           : 5.2.1
timm                 : 0.5.4
torch                : 1.10.2+cu102
torchmetrics         : 0.7.3
tqdm                 : 4.64.0
transformers         : 4.16.2
xgboost              : 1.4.2

```

**Comment by sxjscience** [comment] 2022-05-04 06:41
@Wang-Lin-boop I'm trying to reproduce the issue via the checkpoint you shared. However, it seems to miss `data_processors.pkl` file. Would you also include that?

**Comment by Wang-Lin-boop** [comment] 2022-05-04 06:45
Sorry I thought you just needed to checkpoint ```.ckpt``` files. I've put all the missing files to the same Onedrive address, thanks!

**Comment by sxjscience** [comment] 2022-05-04 06:45
I think I realized the issue. You should load the checkpoint via:

```python
predictor = TextPredictor.load(check_point_name)
```

Instead of

```python
predictor = TextPredictor(...)
predictor.load(path=...)
```

**Comment by sxjscience** [comment] 2022-05-04 06:47
@Wang-Lin-boop Would you try again with the latest command I shared?

**Comment by sxjscience** [comment] 2022-05-04 06:54
@Wang-Lin-boop Submitted a PR to make `load()` a staticmethod.

**Comment by Wang-Lin-boop** [comment] 2022-05-04 07:17
Thank you Xingjian, the new code solved this problem, thanks for your help!

**Comment by Wang-Lin-boop** [comment] 2022-05-04 07:21
It's strange why using the original statement ```predictor_sts.load(path=pretrained_model)``` in training can successfully load checkpoints. ......

**Comment by sxjscience** [comment] 2022-05-04 19:58
Close it for now since it's caused by incorrect usage of the API.

**Closed by sxjscience** 2022-05-04 19:58 UTC
Labels: bug
