### ISSUE TITLE
Memory error in official kaggle tutorial

### ISSUE THREAD

**Issue by qo4on** [awslabs/autogluon#1051] opened 2021-04-09 18:38 UTC
`TabularPredictor().fit` from [this tutorial](https://auto.gluon.ai/stable/tutorials/tabular_prediction/tabular-kaggle.html) doesn't work in `Colab` or in `Kaggle` because of the memory error.
Kaggle has 16.81 GB of available RAM. Autogluon log shows that it needs much less memory: `Train Data (Original)  Memory Usage: 2715.97 MB`
What is the problem?

**Comment by Innixma** [comment] 2021-04-09 20:45
To clarify, the data taking 2.7 GB of memory doesn't mean that AutoGluon won't need more than that to actually train models. You'll likely need 32 GB of memory (such as an m5.2xlarge).

I think it might be good for the tutorial to be updated so it can be run on 16 GB of memory. For example, we have a kaggle kernel that gets top 1% in the Otto competition: https://www.kaggle.com/innixma/autogluon-rapids-top-1

**Comment by qo4on** [comment] 2021-04-09 21:20
Thank you for your answer. I understand that, but the error occures in `Fitting AsTypeFeatureGenerator...`
Are you sure that 11.3 GB of available Colab memory is not enough for feature generation? I successfully trained on 200 000 sampled examples and most of the time memory usage was far from the limit.

Also it's not clear what is the right way for installing AutoGluon. For `Colab` it kind of works with some warnings:
```
!python3 -m pip install -U pip > /dev/null
!python3 -m pip install -U setuptools wheel > /dev/null
!python3 -m pip install -U "mxnet<2.0.0" > /dev/null
!python3 -m pip install autogluon > /dev/null

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
```
The same commands in `Kaggle` return more warnings:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyldavis 3.3.1 requires numpy>=1.20.0, but you have numpy 1.19.5 which is incompatible.
earthengine-api 0.1.258 requires google-api-python-client<2,>=1.12.1, but you have google-api-python-client 1.8.0 which is incompatible.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
transformers 4.4.2 requires tokenizers<0.11,>=0.10.1, but you have tokenizers 0.9.4 which is incompatible.
pdpbox 0.2.1 requires matplotlib==3.1.1, but you have matplotlib 3.4.0 which is incompatible.
jupyterlab-git 0.11.0 requires nbdime<2.0.0,>=1.1.0, but you have nbdime 2.1.0 which is incompatible.
```
And an error on import:
```
----> 3 from autogluon.tabular import TabularPredictor, TabularDataset

/opt/conda/lib/python3.7/site-packages/tornado/iostream.py in BaseIOStream()
    284         self._closed = False
    285 
--> 286     def fileno(self) -> Union[int, ioloop._Selectable]:
    287         """Returns the file descriptor for this stream."""
    288         raise NotImplementedError()

AttributeError: module 'tornado.ioloop' has no attribute '_Selectable'
```

**Comment by Innixma** [comment] 2021-04-09 21:32
It is likely that there is too little memory, 2.7 GB dataset is very large for 15 GB memory, and depending on how you wrote your code, it could be duplicated in memory multiple times (along with having test data in memory). Operations that update DataFrames often also require duplication of the data in memory for the operation, which happens in `AsTypeFeatureGenerator` when converting data types.

Here is a functioning Colab notebook: https://colab.research.google.com/drive/1oT3zNsj9et8s1bJNx7VeHOn_mfpBoe4q?usp=sharing

Here is a functioning Kaggle kernel: https://www.kaggle.com/innixma/top-3-in-1-line-of-code-w-autogluon

**Comment by Innixma** [comment] 2021-04-09 21:33
If you can share the Kaggle Kernel which is causing issues for you on IEEE, that would be a good resource for me to reference.

**Comment by qo4on** [comment] 2021-04-10 12:10
I'm not sure what Kaggle Kernel you are talking about. Just 5 lines of code that return an error in latest Kaggle CPU environment:
![image](https://user-images.githubusercontent.com/35609308/114267353-794c5080-9a14-11eb-99bc-83dff986d543.png)

The code from your Kaggle Kernell works fine:
![image](https://user-images.githubusercontent.com/35609308/114267537-ad744100-9a15-11eb-8024-59b462afddba.png)
As you see `!pip install autogluon.tabular[all]` works fine, but `!pip install autogluon` returns an error.

I tried running the same code in `Colab` and `Kaggle` and found a few issues:
1. Used memory in `Colab` `1.41 GB`, in `Kaggle` `5.06 GB` after the data was loaded. I used separate process to make sure that memory is clear after the data loading.
2. `Kaggle` shows some `DeprecationWarning`.
3. `Kaggle` doesn't show training logs.

`Colab` and `Kaggle` notebooks are in the attachment:
[notebooks.zip](https://github.com/awslabs/autogluon/files/6289787/notebooks.zip).

**Comment by qo4on** [comment] 2021-04-10 20:35
I managed to reduce memory usage for `Colab` to `1.2 GB` and for `Kaggle` to `3.1 GB` using this function:
```
from multiprocessing import Pool

def load_train_data(_):
    train_identity = pd.read_csv(directory + 'train_identity.csv')
    train_transaction = pd.read_csv(directory + 'train_transaction.csv')
    return pd.merge(train_transaction, train_identity, on='TransactionID', how='left')

with Pool(1) as Pool:
    train_data = Pool.map(load_train_data, [None])[0]
```
I have no idea why `Kaggle` needs more memory than `Colab` for the same task.

**Comment by Innixma** [comment] 2021-04-10 21:44
re the error: thanks for this. Looks to be caused by `bokeh`. The latest version has `tornado>=5.1` as a dependency, which upgrades tornado. Since Kaggle doesn't offer an option to restart the runtime while keeping the environment, unlike Colab, an upgrade of tornado causes errors on AutoGluon import.

The following code works on Kaggle:

```
!pip install -U pip
!pip install -U setuptools wheel
!pip install "mxnet<2.0.0"
!pip install "bokeh==2.0.1"
!pip install autogluon
```

I have created PR #1055 to remove bokeh as a dependency, which should hopefully avoid the error.

re Kaggle not showing training logs, I think kaggle just doesn't show any `logger.log()` statements period, which is pretty odd.

For example, it can be minimized to
```
import logging
logging.log(40, 'hello world')
```
which won't show any output on kaggle but will locally or on colab.

**Comment by qo4on** [comment] 2021-04-11 09:44
> Kaggle doesn't offer an option to restart the runtime while keeping the environment

You can do this. First run this:

![image](https://user-images.githubusercontent.com/35609308/114299115-1968af00-9ad3-11eb-84ed-5e489e2b406b.png)

Then restart the runtime while keeping the environment:

![image](https://user-images.githubusercontent.com/35609308/114299183-69477600-9ad3-11eb-971a-32073eab4676.png)

After that import AutoGluon without any error. But the second import shows a warning:

![image](https://user-images.githubusercontent.com/35609308/114299160-474df380-9ad3-11eb-987d-5fc39faaf50c.png)

**Comment by Innixma** [comment] 2021-04-11 20:24
Thats great! I didn't know about those options. Regarding `bokeh`, the PR has been merged, so in the next release there should no longer be an exception on import.

**Comment by qo4on** [comment] 2021-04-14 12:30
Can we get features after preprocessing step? They are all numerical, and they suppose to take less memory. If we do preprocessing in a separate process when the data is loading and then skip preprocessing step in `fit()`, this will help save memory.

**Comment by Innixma** [comment] 2021-04-14 20:45
> Can we get features after preprocessing step? They are all numerical, and they suppose to take less memory. If we do preprocessing in a separate process when the data is loading and then skip preprocessing step in `fit()`, this will help save memory.

Unfortunately, to fit the preprocessing stage features, we need all the data present. There is no 'skipping' it.

However, you can fit the preprocessing prior to calling fit (useful for isolating the memory error):

This example shows how feature generators work: https://github.com/awslabs/autogluon/blob/master/examples/tabular/example_custom_feature_generator.py

To get an identical generator to the one used in `fit` by default:

```
from autogluon.features.generators import AutoMLPipelineFeatureGenerator
feature_generator = AutoMLPipelineFeatureGenerator()
train_data_transformed = feature_generator.fit_transform(X=train_data.drop(columns=[LABEL]))
train_data_transformed[LABEL] = train_data[LABEL]
test_data_transformed = feature_generator.transform(test_data)
test_data_transformed[LABEL] = test_data[LABEL]
```

Then to fit autogluon with the transformed data and avoid performing any preprocessing during fit, replace the default feature generator with a no-op generator (Identity):
```
from autogluon.features.generators import IdentityFeatureGenerator
predictor = TabularPredictor(
    label=LABEL,
    verbosity=2,
).fit(
    train_data=train_data_transformed,
    feature_generator=IdentityFeatureGenerator(),
    time_limit=60,
)

leaderboard = predictor.leaderboard(test_data_transformed)
```

**Closed** 2021-08-14 21:59 UTC
Labels: API & Doc, todo, tabular, kaggle
