### ISSUE TITLE
Autogluon breaks if tried to run it in a script

### ISSUE THREAD

**Issue by wmlba** [awslabs/autogluon#530] opened 2020-06-21 01:40 UTC
Error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/walebadr/Downloads/autogluon.py", line 1, in <module>
    from autogluon import TabularPrediction as task
ImportError: cannot import name 'TabularPrediction'

To Reproduce:
- install latest gluon using pip
- write a very simple script *.py file to do anything.
- run the script.
- autogluon breaks even if you try to run it manually using `python` then `import autogluon`

**Comment by Innixma** [comment] 2020-06-21 02:12
I cannot reproduce this issue.

From a fresh linux machine:

```
python3 -m venv ~/tmp_test
source ~/tmp_test/bin/activate
pip install mxnet
pip install autogluon
python
```

```
Successfully installed ConfigSpace-0.4.10 Pillow-6.2.1 attrs-19.3.0 autogluon-0.0.11 bcrypt-3.1.7 boto3-1.14.7 botocore-1.17.7 catboost-0.23.2 cffi-1.14.0 click-7.1.2 cloudpickle-1.4.1 cryptography-2.9.2 cycler-0.10.0 cython-0.29.20 dask-2.19.0 decorator-4.4.2 distributed-2.19.0 docutils-0.15.2 gluoncv-0.7.0 gluonnlp-0.8.1 heapdict-1.0.1 importlib-metadata-1.6.1 jmespath-0.10.0 joblib-0.15.1 kiwisolver-1.2.0 lightgbm-2.3.1 matplotlib-3.2.2 more-itertools-8.4.0 msgpack-1.0.0 networkx-2.4 packaging-20.4 pandas-0.25.3 paramiko-2.7.1 plotly-4.8.1 pluggy-0.13.1 portalocker-1.7.0 psutil-5.7.0 py-1.8.2 pyaml-20.4.0 pycparser-2.20 pynacl-1.4.0 pyparsing-2.4.7 pytest-5.4.3 python-dateutil-2.8.1 pytz-2020.1 pyyaml-5.3.1 retrying-1.3.3 s3transfer-0.3.3 scikit-learn-0.22.2.post1 scikit-optimize-0.7.4 scipy-1.4.1 six-1.15.0 sortedcontainers-2.2.2 tblib-1.6.0 toolz-0.10.0 tornado-6.0.4 tqdm-4.46.1 typing-3.7.4.1 wcwidth-0.2.4 zict-2.0.0 zipp-3.1.0
```

```
Python 3.7.7 (default, Mar 26 2020, 15:48:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import autogluon
/home/ubuntu/tmp_test/lib/python3.7/site-packages/mxnet/optimizer/optimizer.py:167: UserWarning: WARNING: New optimizer gluonnlp.optimizer.lamb.LAMB is overriding existing optimizer mxnet.optimizer.optimizer.LAMB
  Optimizer.opt_registry[name].__name__))
>>> autogluon.__version__
'0.0.11'
>>> from autogluon import TabularPrediction as task
>>> exit()
```


pip freeze output:

```
attrs==19.3.0
autogluon==0.0.11
bcrypt==3.1.7
boto3==1.14.7
botocore==1.17.7
catboost==0.23.2
certifi==2020.6.20
cffi==1.14.0
chardet==3.0.4
click==7.1.2
cloudpickle==1.4.1
ConfigSpace==0.4.10
cryptography==2.9.2
cycler==0.10.0
Cython==0.29.20
dask==2.19.0
decorator==4.4.2
distributed==2.19.0
docutils==0.15.2
gluoncv==0.7.0
gluonnlp==0.8.1
graphviz==0.8.4
HeapDict==1.0.1
idna==2.9
importlib-metadata==1.6.1
jmespath==0.10.0
joblib==0.15.1
kiwisolver==1.2.0
lightgbm==2.3.1
matplotlib==3.2.2
more-itertools==8.4.0
msgpack==1.0.0
mxnet==1.6.0
networkx==2.4
numpy==1.19.0
packaging==20.4
pandas==0.25.3
paramiko==2.7.1
Pillow==6.2.1
plotly==4.8.1
pluggy==0.13.1
portalocker==1.7.0
psutil==5.7.0
py==1.8.2
pyaml==20.4.0
pycparser==2.20
PyNaCl==1.4.0
pyparsing==2.4.7
pytest==5.4.3
python-dateutil==2.8.1
pytz==2020.1
PyYAML==5.3.1
requests==2.24.0
retrying==1.3.3
s3transfer==0.3.3
scikit-learn==0.22.2.post1
scikit-optimize==0.7.4
scipy==1.4.1
six==1.15.0
sortedcontainers==2.2.2
tblib==1.6.0
toolz==0.10.0
tornado==6.0.4
tqdm==4.46.1
typing==3.7.4.1
urllib3==1.25.9
wcwidth==0.2.4
zict==2.0.0
zipp==3.1.0
```

Please ensure that your installation succeeded and you are using the proper python environment.

Best,
Nick

**Comment by Innixma** [comment] 2020-06-29 21:48
Marking as resolved, please re-open if you still are having issues.

**Closed by Innixma** 2020-06-29 21:48 UTC
Labels: question
